version: '3'

services:
  alphabot:
    container_name: alphabot
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: ${DATABASE_URI}
      TOKEN: ${TOKEN}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - alphabot-db
    networks:
      - alphabot

  alphabot-db:
    container_name: alphabot-db
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - alphabot

volumes:
  postgres_data:

networks:
  alphabot:
    name: alphabot
    driver: bridge
