version: '3'

services:
  alphabot:
    container_name: alphabot
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: ${DATABASE_URI}
      TOKEN: ${TOKEN}
    ports:
      - 8080:8080
    depends_on:
      - postgresql-db
    networks:
      - alphabot

  postgresql-db:
    container_name: postgresql-db
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - alphabot

volumes:
  postgres_data:

networks:
  alphabot:
    name: alphabot
    driver: bridge
